<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>MoleSetup</AssemblyName>
    <RootNamespace>MoleSetup</RootNamespace>
    <Product>摩尔庄园本地客户端 安装引导器</Product>
    <Version>0.1.0</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
